### ISSUE TITLE
Create a Shooter Subsystem

### ISSUE THREAD

**Issue by AlexKaplan1388** [AGHSEagleRobotics/frc1388-2024#14]

**Comment by jtechau** [comment]
As of 27aa102:
- Design is based on a shooter with top/bottom rollers with separate motors for top and bottom
  - We may later decide to change to top/bottom roller pairs with separate motors for left/right instead.
    (This allows for controlling spin of the Note.)
    As such, design of the shooter subsystem should plan for this possibility.
- Shooter subsystem runs both motors together - power based
- Shooter command runs shooter motors until command exits.
  Shooter command has a fixed timeout, then exits.

To Do:
- Shooter needs a feeder?
- Add RPM-based control
- Use separate control for both motors
- Add button bindings for shooter

**Comment by jtechau** [comment]
Shooter subsystem has been implemented and tested.

May still need some tuning and improvement.
