### ISSUE TITLE
Auto-calibrate steering encoder offsets

### ISSUE THREAD

**Issue by AlexKaplan1388** [AGHSEagleRobotics/frc1388-2024#19]
We need a means to determine the offsets for the steering encoders.  These offsets must be non-volatile - that is, they must be applied automatically when the robot powers up, without any user interaction.  There are multiple ways of doing this.  For example:

- Use hardcoded offsets in the code.  This is the current implementation.  The downside is that it requires modifying the code any time the offsets change (due to any hardware change that affects the encoder orientation).
- Use an external command/button/etc to instruct the robot software to calculate the offsets based on the current wheel positions.  These offsets would need to be stored in non-volatile memory on the roboRIO.  (For example, using the [Preferences](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/Preferences.html) class.)
- Configure the magnet offset in the CANCoder to align the zero point of the absolute position reading to the robot's zero angle.  The configuration could be triggered by a button on the robot, or via Phoenix Tuner.

Requirements:

- Offsets must be automatically applied at robot power-up.
- Offsets should be easy to apply.  Ideally this means no programming update is required.  The process must be quick enough to be accomplished in a competition setting (e.g. in the pit between matches, maybe even in the queueing line).
- It must not be easy to accidentally modify the offsets.
- Offsets should be printed to the log and console each time the robot is powered up, and whenever the offsets are updated.

**Comment by MasonGomez1388** [comment]
- Store and retrieve numbers in the roborio
- calculate what the offset should be (new method in SwerveModule) when the user presses a button
- determine when user wants this action to happen
- send this number to the roborio and apply it to the encoder offset
- log the offset values (constructor in DriveTrainSubsystem)

**Comment by jtechau** [comment]
Implemented in eaadce3

It appears that the CANcoder doesn't store configuration in non-volatile memory.
In which case, storing the magnet offset in the CANcoder isn't an option.
Offsets are stored in roboRIO Preferences.
