### ISSUE TITLE
Use Limelight and Coral to vision track game pieces

### ISSUE THREAD

**Issue by AlexKaplan1388** [AGHSEagleRobotics/frc1388-2024#24]
Use the limelight to track and maybe drive toward these game pieces and maybe get certain values from the coral/limelight. Use april tags for now instead of  game pieces, wait until Limelight updates their game piece detection and replace the april tag values for the game pieces.

Progress:
will auto pick up note code is unclear needs review to make sure its working correctly

**Comment by jtechau** [comment]
Working.  May need tuning.
