### ISSUE TITLE
Add arbitrary gyro reset function

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2024#54]
The NavX gyro only provides a way to reset the gyro angle to zero.  We may need to be able to reset the gyro to different robot headings.  For example, the robot may be set up on the field in several different angles; and the driver control to reset the heading may be at yet a different angle.

This can probably be done by passing in a heading offset when resetting the heading, and applying the offset when getting the heading.

See also #46

**Comment by calvinxp** [comment]
done
