### ISSUE TITLE
2/29 auto issue list

### ISSUE THREAD

**Issue by MasonGomez1388** [AGHSEagleRobotics/frc1388-2024#65]
- test shooting from position 1, 2 and 3 before we try auto from those positions. make sure that RPM and shooting angle are known good for each position
- stop driving when note detected in  intake by modifying AutoDrive (and/or AutoDrive to setpoint or whatever it's called)
- modify DeployIntakeCommand (or create a new  AutoIntakeCommand) to also perform functions of RetractIntakeCommand and PullToTransition in a  tri-state machine.
- work on / test auto from position 2 and 3.

**Comment by jtechau** [comment]
Done (?)
