### ISSUE TITLE
Create an Intake Subsystem

### ISSUE THREAD

**Issue by MasonGomez1388** [AGHSEagleRobotics/frc1388-2024#9]
Intake subsystem with neo 550 for intake rollers, another neo 550 for the intake rollers, 3 limit switches, and maybe a sensor.

**Comment by jtechau** [comment]
As of 68188e4:
- Intake subsystem has methods to control roller and lifter motors, and stops lifter motor based on limit switches
- Deploy command lowers intake and starts intake roller
- Retract command raises intake and stops intake roller

To Do:
- Create button bindings for intake commands
- Think about how to manage motor power to raise/lower the intake quickly, but avoid slamming it.
  (Possibly use motor encoder to use position-based power levels)
- Test on the robot

**Comment by jtechau** [comment]
I changed the intake roller motor CAN ID to 19.  See the [Robot Map](https://docs.google.com/spreadsheets/d/1nLzy-j5jzzuXg-XikM7eooYN13HKjaakGQLrkNjXB6Y/edit#gid=0).

**Comment by jtechau** [comment]
Intake subsystem and commands have been implemented.

Still need to adjust the deploy and retract speeds.
